#!/usr/bin/python3
"""Raise exeption with message"""


def raise_exception_msg(message=""):
    """ the function that raise exception with message given
            Args: message(str): the message to printed

    """
    raise NameError(message)
